/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedProgressionRouteImport } from './routes/_authenticated/progression'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedQuizIndexRouteImport } from './routes/_authenticated/quiz.index'
import { Route as AuthenticatedQuizQuizIdRouteImport } from './routes/_authenticated/quiz/$quizId'
import { Route as ApiPublicHooksSendLessonsRouteImport } from './routes/api/public/hooks/send-lessons'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProgressionRoute =
  AuthenticatedProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedQuizIndexRoute = AuthenticatedQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizQuizIdRoute = AuthenticatedQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksSendLessonsRoute =
  ApiPublicHooksSendLessonsRouteImport.update({
    id: '/api/public/hooks/send-lessons',
    path: '/api/public/hooks/send-lessons',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/quiz/': typeof AuthenticatedQuizIndexRoute
  '/api/public/hooks/send-lessons': typeof ApiPublicHooksSendLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/quiz': typeof AuthenticatedQuizIndexRoute
  '/api/public/hooks/send-lessons': typeof ApiPublicHooksSendLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/progression': typeof AuthenticatedProgressionRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/quiz/$quizId': typeof AuthenticatedQuizQuizIdRoute
  '/_authenticated/quiz/': typeof AuthenticatedQuizIndexRoute
  '/api/public/hooks/send-lessons': typeof ApiPublicHooksSendLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/learning'
    | '/progression'
    | '/auth/callback'
    | '/quiz/$quizId'
    | '/quiz/'
    | '/api/public/hooks/send-lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/learning'
    | '/progression'
    | '/auth/callback'
    | '/quiz/$quizId'
    | '/quiz'
    | '/api/public/hooks/send-lessons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/learning'
    | '/_authenticated/progression'
    | '/auth/callback'
    | '/_authenticated/quiz/$quizId'
    | '/_authenticated/quiz/'
    | '/api/public/hooks/send-lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicHooksSendLessonsRoute: typeof ApiPublicHooksSendLessonsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progression': {
      id: '/_authenticated/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AuthenticatedProgressionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/quiz/': {
      id: '/_authenticated/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof AuthenticatedQuizIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/$quizId': {
      id: '/_authenticated/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof AuthenticatedQuizQuizIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/send-lessons': {
      id: '/api/public/hooks/send-lessons'
      path: '/api/public/hooks/send-lessons'
      fullPath: '/api/public/hooks/send-lessons'
      preLoaderRoute: typeof ApiPublicHooksSendLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedProgressionRoute: typeof AuthenticatedProgressionRoute
  AuthenticatedQuizQuizIdRoute: typeof AuthenticatedQuizQuizIdRoute
  AuthenticatedQuizIndexRoute: typeof AuthenticatedQuizIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedProgressionRoute: AuthenticatedProgressionRoute,
  AuthenticatedQuizQuizIdRoute: AuthenticatedQuizQuizIdRoute,
  AuthenticatedQuizIndexRoute: AuthenticatedQuizIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicHooksSendLessonsRoute: ApiPublicHooksSendLessonsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
