DO $$
DECLARE
    q_list jsonb := (SELECT questions FROM public.quizzes WHERE id = 8);
BEGIN
    -- Part 1
    q_list := q_list || '[{"id": 1, "question": "(Q1) Quelle est la durée légale du travail hebdomadaire en France selon la Partie Législative ?", "options": ["35 heures par semaine", "39 heures par semaine", "40 heures par semaine", "32 heures par semaine"], "correct_index": 0, "casus": "[Heures supplémentaires] Un salarié travaillant dans une entreprise de logistique effectue 39 heures de travail effectif au cours d''une semaine donnée. Il demande à son employeur comment sont décomptées les heures au-delà de la durée légale.", "reference": "Art. L3121-27", "article": "La durée légale du travail effectif des salariés à temps complet est fixée à trente-cinq heures par semaine."}, {"id": 2, "question": "(Q2) Selon l''article L1152-1, qu''est-ce qui caractérise le harcèlement moral ?", "options": ["Des agissements répétés dégradant les conditions de travail", "Une simple mésentente ponctuelle", "Une exigence de productivité élevée", "Un changement de bureau non souhaité"], "correct_index": 0, "casus": "[Harcèlement moral] Un salarié reçoit de façon répétée des remarques désobligeantes de son supérieur hiérarchique devant ses collègues, ce qui affecte gravement sa santé mentale et sa motivation.", "reference": "Art. L1152-1", "article": "Aucun salarié ne doit subir les agissements répétés de harcèlement moral qui ont pour objet ou pour effet une dégradation de ses conditions de travail susceptible de porter atteinte à ses droits et à sa dignité, d''altérer sa santé physique ou mentale ou de compromettre son avenir professionnel."}]'::jsonb;
    -- Part 2
    q_list := q_list || '[{"id": 3, "question": "(Q3) Quelle est la durée maximale initiale de la période d''essai pour un cadre en CDI ?", "options": ["4 mois", "2 mois", "3 mois", "6 mois"], "correct_index": 0, "casus": "[Période d''essai (CDI)] Un cadre est embauché en CDI. Son contrat prévoit une période d''essai initiale. Il s''interroge sur la durée maximale légale autorisée pour son statut.", "reference": "Art. L1221-19", "article": "Le contrat de travail à durée indéterminée peut comporter une période d''essai dont la durée maximale est de : 1° Deux mois pour les ouvriers et les employés ; 2° Trois mois pour les agents de maîtrise et les techniciens ; 3° Quatre mois pour les cadres."}, {"id": 4, "question": "(Q4) Combien de jours ouvrables de congés payés un salarié acquiert-il par mois de travail effectif ?", "options": ["2,5 jours ouvrables", "2 jours ouvrables", "3 jours ouvrables", "1,75 jours"], "correct_index": 0, "casus": "[Congés payés] Un salarié a travaillé durant toute la période de référence (12 mois). Il souhaite savoir combien de jours de congés payés il a acquis au total.", "reference": "Art. L3141-3", "article": "Le salarié a droit à un congé de deux jours et demi ouvrables par mois de travail effectif chez le même employeur. La durée totale du congé exigible ne peut excéder trente jours ouvrables."}]'::jsonb;
    
    UPDATE public.quizzes SET questions = q_list WHERE id = 8;
END $$;